Repository ssuperpower-developer/GitPracticeProject, pull requests merged in 2022-07, with the labels that each got.

#2 [Feat] 생성자, 복사 생성자 함수 작업 완료+[Refactoring] main.cpp의 코드를 Account.cpp로 이동
  .gitignore
  Account.cpp
  Account.h
  main.cpp
Labels: enhancement

#3 [Add] Withdraw 함수 완성
  Withdraw.cpp
Labels: enhancement

#4 [Feat] Deposit 함수 작업 완료
  Deposit.cpp
Labels: enhancement

#9 [Docs] main 파일 수정 & gitignore 수정
  .gitignore
  main.cpp
Labels: documentation, enhancement

#10 [Docs] Edit README
  README.md
Labels: documentation

#20 [Refactoring & Docs] 전체적인 파일 수정 및 코드 오류 수정
  .gitignore
  Account.cpp
  Account.h
  AccountHandler.h
  Accounthandler.cpp
  main.cpp
Labels: bug, documentation, enhancement, check

#22 [Feat] MakeAccount()와 ShowMenu() 함수를 기능 추가
  Account.cpp
  Accounthandler.cpp
Labels: enhancement
